version: '3'

services:

  mysql-dev:
    image: mysql:8.0.2
    enviromment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_home
    ports:
      - "3308:3306"
  
version: '3'

services:
  mysql-container:
    image: mysql:8.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_home
    ports:
      - "3308:3306"
    volumes:
      - "./my.conf:/etc/mysql/conf.d/config-file.cnf"
      - "./data:/var/lib/mysql:rw"